<?php

require $_SERVER['DOCUMENT_ROOT'].'/assets/php/include.php';
require 'session.php';

session_startsecure();

switch ($_SERVER['REQUEST_METHOD']) {
    case 'POST':
        header('Content-type: application/json');

        $return = array();
        $db = new Db();
        $user = $db->query(
            'SELECT id, password, password_expires FROM users WHERE email=(?)',
            's',
            $_POST['email']
        );
        if (isset($_GET['type']) && $_GET['type'] == "generate") {
            $password = mt_rand(100000, 999999);
            if (count($user) === 0) {
                $return['type'] = 'error';
                $return['text'] = 'Email not found!';
            } else {
                $db->query(
                    "UPDATE users SET password=(?), password_expires=(?) WHERE email=(?)",
                    "isi",
                    $password,
                    time()+300,
                    $_POST['email']
                );
                $sendMail = mail(
                    $_POST['email'],
                    'New password',
                    'Generated by: ' . $_SERVER['REMOTE_ADDR'] . "\r\n" .
                    'Password: '. $password . "\r\n" .
                    'This password will be invalid five minutes after genration',
                    'From: manage@swampbotics.org' . "\r\n" .
                    'Reply-To: manage@swampbotics.org' . "\r\n" .
                    'X-Mailer: PHP/' . phpversion()
                );
                $return['type'] = 'success';
                $return['text'] = 'Check your email! Status: ' . ($sendMail ? 'Sent' : 'Failed');
            }
        } else {
            if (count($user) === 0 || $_POST['password'] !== $user[0]['password']) {
                $return['type'] = 'error';
                $return['text'] = 'Invalid email or password!';
                echo json_encode($return);
                exit;
            }
            if ($user[0]['password_expires'] < time()) {
                $return['type'] = 'error';
                $return['text'] = 'Your password has expired';
                echo json_encode($return);
                exit;
            }
            $return['type'] = 'success';
            $return['text'] = 'Successfully logged in!';
            $_SESSION['userid'] = $user[0]['id'];
            $db->query('UPDATE users SET password_expires=(?) WHERE id=(?)', 'ii', time(), $user[0]['id']);
        }
        echo json_encode($return);

        break;
    default:
        if (isset($_SESSION["userid"])) {
            header("Location: /");
        }
        $thisPage = new Page();
        $thisPage->meta = '';
        $thisPage->nav = false;
        $thisPage->title = $autoTitle;
        $header = str_replace(
            array(
                '{page}'
            ),
            array(
                $thisPage->title
            ),
            file_get_contents($_SERVER['DOCUMENT_ROOT'].'/assets/html/headers/manage.html')
        );
        $thisPage->header = $header;
        $thisPage->js = '<script src="assets/js/custom/manage.js"></script>';
        $thisPage->content = file_get_contents($_SERVER['DOCUMENT_ROOT'].'/assets/html/pages/manage/login.html');
        $thisPage->output();
}
